<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_v.bmail.com</name>
   <tag></tag>
   <elementGuidId>5ad0752b-b20b-4f6a-9e97-1e4354debf75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email > ul.list-group.list-group-flush.mb-2 > li.list-group-item.px-0 > div.d-flex.align-items-center > div.col.ms-2 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email']/ul/li/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71ca1a17-c265-4569-ac60-1c2380906b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:v.b@mail.com</value>
      <webElementGuid>2152d710-8c4b-4f11-a700-b882a82dff15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>v.b@mail.com</value>
      <webElementGuid>c98672ea-693f-4315-9531-53a080e19746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email&quot;)/ul[@class=&quot;list-group list-group-flush mb-2&quot;]/li[@class=&quot;list-group-item px-0&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;col ms-2&quot;]/a[1]</value>
      <webElementGuid>6f1ace16-77ea-4b1e-a9e7-0d574f0e9a3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email']/ul/li/div/div[2]/a</value>
      <webElementGuid>23800384-fad7-44fd-90dc-0bd306261b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'v.b@mail.com')]</value>
      <webElementGuid>5ca019ab-eb0e-4fd5-839f-66513faf31c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='At least one email address is required.'])[1]/following::a[2]</value>
      <webElementGuid>e06ce9ab-af2d-45d9-9255-34e64c00d38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::a[2]</value>
      <webElementGuid>5f7fa45c-3baf-4120-b6f7-c346ee97d581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address:'])[1]/preceding::a[1]</value>
      <webElementGuid>2653eba1-ef51-4fba-a77a-97ed161da264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Park, New York, NY 98502, USA'])[1]/preceding::a[1]</value>
      <webElementGuid>114db05d-38a3-4882-a99f-76c5aea1bd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='v.b@mail.com']/parent::*</value>
      <webElementGuid>e3b54edc-2941-47a5-8666-d490279d1ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:v.b@mail.com')]</value>
      <webElementGuid>20224005-afd3-4407-aae5-48025ebfc37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/div/div[2]/a</value>
      <webElementGuid>dd5210ef-2528-4260-9e50-0352f9de5e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:v.b@mail.com' and (text() = 'v.b@mail.com' or . = 'v.b@mail.com')]</value>
      <webElementGuid>4fbbdcff-648f-4c4a-918c-767886e262c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
