<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_full-name</name>
   <tag></tag>
   <elementGuidId>98ba5eb5-6abc-439c-8a88-3b4dd7f2ef95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#full-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='full-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6141e81-b1e9-4314-8deb-185c5139c5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>full-name</value>
      <webElementGuid>29ef4501-4680-4c56-a051-53aab971f70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f76ef925-2511-4f2f-8612-ab3d725ed36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ca79004-59fd-4e6f-9721-b7e6e9309e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;full-name&quot;)</value>
      <webElementGuid>8b48b4d0-473f-4d27-8a5b-15a4b54ac967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='full-name']</value>
      <webElementGuid>3b61c9e7-9f8f-4378-8d8b-55ae9c4738b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/form/div/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e7177cf1-dc23-4202-8684-8d9e0d254780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>ae82aa36-a879-4938-b14e-519d1155a6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'full-name' and @type = 'text']</value>
      <webElementGuid>9a7ae659-d2cc-44e6-935e-7c088759eedb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
