<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Email</name>
   <tag></tag>
   <elementGuidId>ce627fd3-f3f7-4bb5-bda9-9ff070333ef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/form/div/div/div[2]/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e91bd913-cd5b-416a-a225-88521d9758d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>234694d2-c94e-4773-bb80-cb63f02fc5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-3 col-form-label</value>
      <webElementGuid>2639b7c4-2963-4c7e-b93e-df81e2ce8dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email:</value>
      <webElementGuid>0361743b-1a41-4578-b02f-637c0733cb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-wrapper d-flex flex-column h-100&quot;]/main[@class=&quot;flex-fill overflow-auto&quot;]/div[@class=&quot;container-fluid&quot;]/form[@class=&quot;bottom-border-input&quot;]/div[@class=&quot;row mb-3&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;card w-100 mb-3&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row mb-1&quot;]/label[@class=&quot;col-sm-3 col-form-label&quot;]</value>
      <webElementGuid>de147e6e-b400-4d47-a197-06e2a8489fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/form/div/div/div[2]/div/div[2]/label</value>
      <webElementGuid>4c8ef009-0b69-4edf-82ae-8762e9e2bfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W 277982398'])[1]/following::label[1]</value>
      <webElementGuid>d5d22150-dcb2-45ff-a1c7-3780e8721c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='At least one phone is required.'])[1]/following::label[1]</value>
      <webElementGuid>e52e7df1-484e-41e0-97ff-9a54be9384b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='At least one email address is required.'])[1]/preceding::label[1]</value>
      <webElementGuid>161820aa-a715-43bd-953a-41c2f60c4653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v.p@mail.com'])[1]/preceding::label[1]</value>
      <webElementGuid>9922ce86-aab1-4b3a-9c74-686f65bf9ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email:']/parent::*</value>
      <webElementGuid>8a7c1e39-8df3-4a5c-ad12-9040827adcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/label</value>
      <webElementGuid>3c02e6ae-1443-4863-8bae-616f03d9f783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Email:' or . = 'Email:')]</value>
      <webElementGuid>e425db0e-5b9e-4576-b035-cef4a3c2773b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
