<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_ctl00ctl00mainContentCon_c07fc0</name>
   <tag></tag>
   <elementGuidId>e2ebe860-3483-45e9-8969-49765b405172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c7a4b59-358a-44bd-adca-7d545f76177c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$txtPhone</value>
      <webElementGuid>f90d8068-1949-43ce-8f75-cb3ebde20377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone</value>
      <webElementGuid>f4beabc7-28cd-4edc-8821-b5b73ddb3f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2353d3bf-090a-450d-aba6-c2683f8661d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f5e235a8-72bd-463c-9b96-0362af191444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>intlPhoneInput_ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone.api.setNumber(this.value);</value>
      <webElementGuid>aa675971-e363-4fc7-8ccf-dc6279aa9a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0edfb089-7aaf-4006-bee9-073e8e1df548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>074104 10123</value>
      <webElementGuid>8cdedf14-b3b0-49b6-b209-75cc7895fa15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ef784068-f4e2-45b0-8238-ffbc61adb9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone&quot;)</value>
      <webElementGuid>4a8461d9-e34b-4108-90c5-05ff74d124b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone']</value>
      <webElementGuid>9285e505-7f4b-4301-8042-c374e4d39e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone-wrapper']/div/input</value>
      <webElementGuid>d890b577-f1f5-41b7-8446-141d68590231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/input</value>
      <webElementGuid>33eda8b0-0180-4d8c-b4ab-6f8a5787bba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$txtPhone' and @id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_txtPhone' and @type = 'tel' and @placeholder = '074104 10123']</value>
      <webElementGuid>d591f443-66e6-4cfc-a68f-ad11f42adebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
