<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_ctl00ctl00mainContentCon_7609b5</name>
   <tag></tag>
   <elementGuidId>1fe20743-c788-4748-8eed-9015ecd87963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>220ab6f8-9e8b-4805-b95b-2ec59e7b40fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$txtCompanyName</value>
      <webElementGuid>0197e634-1710-4367-8dab-2cf66afd3b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>046ab9ce-18b7-4b27-b7fe-6263b413797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$ctl00$mainContent$ContentPlaceHolder1$txtCompanyName\',\'\')', 0)</value>
      <webElementGuid>14aef5f9-d1c7-420a-9016-82b2abe19547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;</value>
      <webElementGuid>933efdfc-b7c4-4584-b56c-5548d0f5b3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName</value>
      <webElementGuid>c6a38899-f533-495d-904d-ff54df47853e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>2aece6ac-5e6e-4e39-97e4-c577f2e6a69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName&quot;)</value>
      <webElementGuid>67fd0566-e7e4-4304-b152-e165347e36b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName']</value>
      <webElementGuid>2c85a9e4-7974-4a1c-8ea9-e7bbb02ecb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyNamePanel']/input</value>
      <webElementGuid>26f7d086-380e-4e4f-b73c-f0874d804a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>9ee9dad9-4801-4023-a84c-a4c1af524672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$txtCompanyName' and @type = 'text' and @id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_txtCompanyName']</value>
      <webElementGuid>8500ea8e-d9cd-4f09-a25b-51f68a349861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
