<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_test.striven.com_ctl00ctl00mainConten_d264b4</name>
   <tag></tag>
   <elementGuidId>1169dc51-07d4-4e8f-82e3-4187e39f9c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_ContentPlaceHolder1_btnGetStarted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_btnGetStarted']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8033de02-34ba-4b22-8caa-75df60b76787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>264e3d52-9899-4cdd-af0a-93950cb63bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$ContentPlaceHolder1$btnGetStarted</value>
      <webElementGuid>ff84b102-3cb8-4ecd-ac3f-76214644bb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go to My Dashboard</value>
      <webElementGuid>f3aa6d3a-3f4c-4cf2-b1b5-fef86434f2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ctl00$mainContent$ContentPlaceHolder1$btnGetStarted&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>a089da8d-8478-42ec-85f9-90ad42b5d9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_ContentPlaceHolder1_btnGetStarted</value>
      <webElementGuid>94eb1788-8fba-4ca5-bbbb-5f1502e2215c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg</value>
      <webElementGuid>565ceb6f-fe39-4b80-b0e9-645a90a91b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_ContentPlaceHolder1_btnGetStarted&quot;)</value>
      <webElementGuid>c015a62c-386b-49be-9533-1ed0b0dd518e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_ContentPlaceHolder1_btnGetStarted']</value>
      <webElementGuid>826f26f7-d085-42d0-af43-b699102d5eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bg-div']/div/div[4]/input</value>
      <webElementGuid>bdb37846-08e6-4950-ae59-fce8bd7a87c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>f83206b1-dfca-4ea6-ac2c-e0ef6d8e87fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ctl00$mainContent$ContentPlaceHolder1$btnGetStarted' and @id = 'ctl00_ctl00_mainContent_ContentPlaceHolder1_btnGetStarted']</value>
      <webElementGuid>be1be421-1221-468f-9957-0d2db4ec0e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
