<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Striven Website_rounded-circle show_1</name>
   <tag></tag>
   <elementGuidId>d1b44ac7-7e25-494c-b620-f18bce9a35f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/div[6]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0d9312df-3caf-4de8-acf6-74f788ea1365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ae6550a-6f86-47e0-bc51-73806e6e29eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/api/core/profile-image?v=1681036188772</value>
      <webElementGuid>d6ad39e9-da30-49c2-befe-6b9a79caf510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle show</value>
      <webElementGuid>07d9ec56-73ec-4eb7-8de9-401ada1510d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Employee Actions</value>
      <webElementGuid>ea789969-937e-47ed-8476-7ee499b9134a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>80e810da-ee2f-406a-a453-dbd61b114c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7171279-3da1-41f2-8be5-73a6111fc19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-wrapper d-flex flex-column h-100&quot;]/header[@class=&quot;layout-header&quot;]/div[@class=&quot;px-0 py-1 px-xl-3 py-xl-1 d-flex align-items-center border-bottom&quot;]/div[@class=&quot;me-3 btn-group&quot;]/img[@class=&quot;rounded-circle show&quot;]</value>
      <webElementGuid>b0bc3f2b-e3b8-43e0-a5cc-9e27593eee32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/div[6]/img</value>
      <webElementGuid>b13f93b4-b916-4d0a-a96d-d77f39692a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Employee Actions']</value>
      <webElementGuid>117ae4f4-0bd2-40c0-ae1a-07d7acd5e6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/img</value>
      <webElementGuid>c9ee6ed2-af99-452c-af64-4ebd06c0f221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/api/core/profile-image?v=1681036188772' and @title = 'Employee Actions']</value>
      <webElementGuid>907ec151-7677-4ca8-9632-44667457b89c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
