<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Striven Website_rounded-circle show</name>
   <tag></tag>
   <elementGuidId>e019ace4-ba71-409f-8fb3-2913130b2f0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/div[6]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d13f4486-8fdf-4ced-b132-baf37a017095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9356b1c4-0b9b-4783-84b2-e8aaf2593f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/api/core/profile-image?v=1681033211169</value>
      <webElementGuid>76466971-1a34-45b1-95f8-dafa77e31ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle show</value>
      <webElementGuid>e53d2d3a-c277-4811-8839-c56a848e40c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Employee Actions</value>
      <webElementGuid>61d6f323-8ab0-484a-8b89-a9bf1b797e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>28e63b4d-4f34-4d0e-a095-f6483adde9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c2261fd-b166-42cc-9d26-39d9821b92de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-wrapper d-flex flex-column h-100&quot;]/header[@class=&quot;layout-header&quot;]/div[@class=&quot;px-0 py-1 px-xl-3 py-xl-1 d-flex align-items-center border-bottom&quot;]/div[@class=&quot;me-3 btn-group&quot;]/img[@class=&quot;rounded-circle show&quot;]</value>
      <webElementGuid>b6670575-7c07-461c-9b85-5515c7ac52e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/div[6]/img</value>
      <webElementGuid>b9816b40-b9c9-41d6-ac30-36800d33f55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Employee Actions']</value>
      <webElementGuid>7d67e693-636d-4891-9c69-dd0842f2fbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/img</value>
      <webElementGuid>ed55dc17-77e1-4045-964a-b8917744ecd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/api/core/profile-image?v=1681033211169' and @title = 'Employee Actions']</value>
      <webElementGuid>46b4a917-a2fc-4ef1-ad8d-f348df2b7d36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
