<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Striven Website_img-circle</name>
   <tag></tag>
   <elementGuidId>de9d6014-b116-4f55-95d9-b81f1c5e6a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5b363423-6aea-4397-9e09-418b346962c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>671e1bba-c183-48e0-a196-0f36f8b6ee39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/no_profile_image.png</value>
      <webElementGuid>8a473d34-719c-4a65-a2b6-9e1853ad5488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture&quot;)/img[@class=&quot;img-circle&quot;]</value>
      <webElementGuid>c5aae1ce-8125-4725-8d42-e83f6f7e784e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_MainHeader_HeaderSection_imgPicture']/img</value>
      <webElementGuid>c0ceb373-4c2a-4389-8589-d036e619fb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>5f4a4a84-7ed2-453d-8c9c-56a8ddd5af4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/no_profile_image.png']</value>
      <webElementGuid>2e2cf17a-742b-45c9-92f2-24dbdd3163d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
