<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your email address or password is incor_e950e2</name>
   <tag></tag>
   <elementGuidId>84189d7c-8d11-4f2e-97e8-25517dfa9a89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jGrowl-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jGrowl']/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6772c41c-2c9f-49d9-83f9-d372278e07c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jGrowl-message</value>
      <webElementGuid>81126b2f-b5b1-4ea1-b549-1bacf6652ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your email address or password is incorrect. Please try again.</value>
      <webElementGuid>b8d5f1ec-c888-493b-9794-a94a420d64db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jGrowl&quot;)/div[@class=&quot;jGrowl-notification alert ui-state-highlight ui-corner-all errorMsg&quot;]/div[@class=&quot;jGrowl-message&quot;]</value>
      <webElementGuid>6bae2cb2-dbee-4261-a36a-c8f1bc990250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jGrowl']/div[2]/div[2]</value>
      <webElementGuid>a2e0a71c-963b-4fec-af9e-853edf97d064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::div[1]</value>
      <webElementGuid>041aeebd-95ce-4c39-8a86-3ce15c1cbfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[2]</value>
      <webElementGuid>750a7c49-7e57-4d0f-acbf-70d97aa062db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your email address or password is incorrect. Please try again.']/parent::*</value>
      <webElementGuid>7c3fa9ed-40c4-4d16-aa24-d2e8ba9d85e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div[2]/div[2]</value>
      <webElementGuid>1cd604e4-9f72-496a-8dee-42a2fea10ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your email address or password is incorrect. Please try again.' or . = 'Your email address or password is incorrect. Please try again.')]</value>
      <webElementGuid>9693ae0c-8cf6-4627-904a-4e51a48ac44f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
