<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EMAIL_ctl00mainContenttxtEmail</name>
   <tag></tag>
   <elementGuidId>a77fb3a6-726c-454f-97be-0b87a837c737</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainContent_txtEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_txtEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bdc325d-f53e-4884-8a25-f5636623b4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$mainContent$txtEmail</value>
      <webElementGuid>f375cbb0-ac69-4e7b-b3b6-07e751d0150b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1abc83f0-5836-4dbd-becd-decae001c9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>898fc9b5-f114-42e4-9387-ae5edf30e453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_txtEmail</value>
      <webElementGuid>86720e56-b70b-4d3c-9d20-ed2a92cf3140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg invalid-control</value>
      <webElementGuid>207cb343-8299-4ea8-a4bc-dd8dfccc1da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business Email*</value>
      <webElementGuid>47ccda81-be23-4af8-8e6c-6e6826c01eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_txtEmail&quot;)</value>
      <webElementGuid>4e6c64b1-0df7-4133-a9d7-56e4e4da486e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_txtEmail']</value>
      <webElementGuid>0859dc7b-435a-496a-ab01-ce4170dfda34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_pnlSignupEntry']/div[2]/div/div[5]/div/input</value>
      <webElementGuid>b2deaea3-1ff0-4f04-bb69-b90218647ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>7c8786e2-0d87-44f5-b78c-a2d483bd911a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$mainContent$txtEmail' and @type = 'text' and @id = 'mainContent_txtEmail' and @placeholder = 'Business Email*']</value>
      <webElementGuid>13589c5e-eabf-4efc-a646-69fa9fe513f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
