<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_ctl00ctl00mainContentmainCont_49a1e1</name>
   <tag></tag>
   <elementGuidId>9f4c10a7-4cc2-48b4-b78c-6de9af63ee4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainContent_mainContent_txtEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_mainContent_txtEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2c1ce0f-acb2-4ab2-8d6b-5b868efe3caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$txtEmail</value>
      <webElementGuid>0e5e6912-4b76-425f-9ca9-df4f146df474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>97841144-486d-401f-83cc-117e237186b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_mainContent_txtEmail</value>
      <webElementGuid>349ed095-6a33-492b-82eb-404d659222b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>12da7cb6-b33c-47ae-b31b-06b6fa587c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>example@domain.com</value>
      <webElementGuid>cec6b770-4736-4d13-80b0-51fe32eb7368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_txtEmail&quot;)</value>
      <webElementGuid>78381b29-fb0f-4c57-b4cc-8d50007ccf2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_mainContent_txtEmail']</value>
      <webElementGuid>76e4b592-13f0-463c-bed3-e3862428a472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_mainContent_pnlMemeberLogIn']/div/div/div/input</value>
      <webElementGuid>caeae625-40c1-4cfc-9251-1f03fb5f9ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>1645d5fb-add6-46f2-8fa5-2aecc970641e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$mainContent$txtEmail' and @type = 'email' and @id = 'mainContent_mainContent_txtEmail' and @placeholder = 'example@domain.com']</value>
      <webElementGuid>a7f9245b-d3e8-4ce3-8db5-e7f26590a1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
