<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_ctl00ctl00mainContentmainCont_755761</name>
   <tag></tag>
   <elementGuidId>0c59e395-63e1-4e02-a1a9-aed6e70eefb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainContent_mainContent_txtPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_mainContent_txtPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>212b876a-7c92-4331-b542-4a444002e254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$txtPassword</value>
      <webElementGuid>01d26ed3-455e-4296-b18f-5b29b6254dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1b0f47b4-f6ed-4d04-9dbc-7439e940fa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_mainContent_txtPassword</value>
      <webElementGuid>520c50be-3b63-49ee-b2f4-b0fa05d77130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a92f1d0d-201c-4616-82cb-28ef88964d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>cbdcf696-7bd2-4e1b-a962-18d6cff6c176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_txtPassword&quot;)</value>
      <webElementGuid>63b7ede1-2a49-4ce4-9d18-87804cea6546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_mainContent_txtPassword']</value>
      <webElementGuid>81f57b75-35ee-4176-8175-d3459c44d3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_mainContent_pnlMemeberLogIn']/div/div/div[2]/input</value>
      <webElementGuid>fb3eb795-80c2-4787-b0d2-8ec775350337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>c859c7f6-2c3b-437b-bc55-2775a66446ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$mainContent$txtPassword' and @type = 'password' and @id = 'mainContent_mainContent_txtPassword' and @placeholder = 'Password']</value>
      <webElementGuid>3e84caa5-e894-41c0-8ba4-94197ad85a42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
