<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EMAIL_ctl00mainContentbtnStart_input</name>
   <tag></tag>
   <elementGuidId>f7f73f74-232c-4e31-9bcf-62186e0f96aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_mainContent_btnStart_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_mainContent_btnStart_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4bccdaf-925f-48b0-b8bc-0b8048cd9ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rbDecorated</value>
      <webElementGuid>3b81662d-9a96-49ac-9902-52622d9eddf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f6ac1a2-3603-4333-8428-f7ffa85fd347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$mainContent$btnStart_input</value>
      <webElementGuid>c2a70843-a2ea-402a-b69a-1b233c17f24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_mainContent_btnStart_input</value>
      <webElementGuid>d17c070e-e27f-4822-b14f-828b1f25fafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Get Started</value>
      <webElementGuid>b744771d-f7a7-4f27-8227-30ae59de8c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ee68487a-26b1-45da-86ca-3e47c2a39715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_btnStart_input&quot;)</value>
      <webElementGuid>4e2e889c-768f-4aee-91a6-8a8bb475f318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_mainContent_btnStart_input']</value>
      <webElementGuid>ad8a1221-6f9a-4063-9f3a-e1240c75669e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_mainContent_btnStart']/input</value>
      <webElementGuid>adcf616d-8c9a-4668-9249-113a03985046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>1ae6d1f0-d4ef-4928-b2e5-eb2da3b08128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'ctl00$mainContent$btnStart_input' and @id = 'ctl00_mainContent_btnStart_input']</value>
      <webElementGuid>a5b36dea-cc7d-42a0-83e2-fa784e84ba0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
