<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LAST NAME_ctl00mainContenttxtLastName</name>
   <tag></tag>
   <elementGuidId>8d3b9f86-2557-455c-8a39-e23a52350cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainContent_txtLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_txtLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f38a89b-81cc-4090-8add-5b3fad816e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$mainContent$txtLastName</value>
      <webElementGuid>5d4e6c2b-6afb-43d1-88f3-869c73bf73e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd2c9eef-b755-400f-8c66-4e4e9c170662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>40babdcb-bd73-4e60-ab18-6bf53de61596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_txtLastName</value>
      <webElementGuid>558b620a-2750-4d47-90b1-3a9f88330f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg invalid-control</value>
      <webElementGuid>19f588b0-7781-4df0-ad23-9b6c5638a2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name*</value>
      <webElementGuid>32433dc9-cc31-49db-bb55-55788b3baef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_txtLastName&quot;)</value>
      <webElementGuid>ab06c999-4bcc-4003-801a-0791d96c0bea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_txtLastName']</value>
      <webElementGuid>8b657884-4acc-4348-8a15-da7e4bece1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_pnlSignupEntry']/div[2]/div/div[4]/div/input</value>
      <webElementGuid>daab8b96-4ca8-4d4e-ab50-bbdd999b96b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a6472e4d-3630-4157-a405-7fd05d53e8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$mainContent$txtLastName' and @type = 'text' and @id = 'mainContent_txtLastName' and @placeholder = 'Last Name*']</value>
      <webElementGuid>8e68c755-4370-428a-b1f0-5ac4e5334919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
