<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember this device for 30 days_ctl0_098541</name>
   <tag></tag>
   <elementGuidId>e31d6afc-c2b6-4a2a-af4f-10dfaebbf183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainContent_mainContent_CodeTextBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_mainContent_CodeTextBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57fafb2a-f3bf-46d9-a98f-92a3865ac4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$CodeTextBox</value>
      <webElementGuid>61737247-95dd-46c3-a2e4-c963cd548195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e8e26b2-cd04-42d3-b2ba-c337cc21fd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>08ceadfa-7406-4005-84b8-6eb5fa5ab8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_mainContent_CodeTextBox</value>
      <webElementGuid>3b11ad9c-ec13-4617-8813-3fedb6b9ef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4e08e39a-fa99-45e4-aba2-77dd715b9114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter security code</value>
      <webElementGuid>dd098dad-d56d-402c-9657-62965c925196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_CodeTextBox&quot;)</value>
      <webElementGuid>3722825b-888c-461d-ab55-296b94519e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_mainContent_CodeTextBox']</value>
      <webElementGuid>f8638a0d-317b-4fee-ad77-125d43396927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_mainContent_CodeEntryPanel']/input</value>
      <webElementGuid>a4e07548-6f39-4ce0-b2d8-34a4ad70c64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3eae353b-0eb6-47f3-914d-21b9c12b18f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$mainContent$CodeTextBox' and @type = 'text' and @id = 'mainContent_mainContent_CodeTextBox' and @placeholder = 'Enter security code']</value>
      <webElementGuid>cbb01119-7f49-4009-95a9-4843078244f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
