<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FIRST NAME_ctl00mainContenttxtFirstName</name>
   <tag></tag>
   <elementGuidId>76d4e540-2a4c-4956-ae2e-d606f156e986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainContent_txtFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_txtFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46416dad-fa21-41e3-b916-10c9d85dafef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$mainContent$txtFirstName</value>
      <webElementGuid>e6acc56e-9bde-4000-83c3-a026ad11d1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>898a079a-b039-49eb-850e-2fad5f61adc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e84c9fcc-c70c-489f-a98d-a52c01bb139b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_txtFirstName</value>
      <webElementGuid>7d59341f-1d2f-4db5-ad62-19cfa8ef0d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg invalid-control</value>
      <webElementGuid>684c870b-e2b5-4158-9e48-037d831447f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name*</value>
      <webElementGuid>4775f16b-e257-48e8-ab76-52f0e14051b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_txtFirstName&quot;)</value>
      <webElementGuid>71b6702e-4347-49aa-9dea-3fd53396fb7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_txtFirstName']</value>
      <webElementGuid>0336dc1d-4b71-4b47-83ba-6efe85e01d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_pnlSignupEntry']/div[2]/div/div[3]/div/input</value>
      <webElementGuid>f4f96bf8-ba72-4ec6-a535-261433c04a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>722bf062-06d2-4e2d-b062-b972be29609e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$mainContent$txtFirstName' and @type = 'text' and @id = 'mainContent_txtFirstName' and @placeholder = 'First Name*']</value>
      <webElementGuid>266f18c7-c9d7-45a6-b9b8-71dc9d419694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
