<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login and Signup</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>nsawant@striven.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8624400d-6ec7-4b01-b128-1d95f4c6282e</testSuiteGuid>
   <testCaseLink>
      <guid>c500eee4-3975-4fea-bc06-ab616a3a76ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Cases_Final/Login and Signup/Login_TestCases</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9de3cf3b-fb3f-439e-88aa-72702817c119</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3,4</value>
         </iterationEntity>
         <testDataId>Data Files/Striven_Users</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9de3cf3b-fb3f-439e-88aa-72702817c119</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Login_Email</value>
         <variableId>69c9e28d-93cf-4a50-9399-ae2272395f0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9de3cf3b-fb3f-439e-88aa-72702817c119</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>fa3964cd-dce4-490c-9920-f7a9395faa7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9de3cf3b-fb3f-439e-88aa-72702817c119</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>URL</value>
         <variableId>bdc69ea0-5c1d-4c99-94fc-36e913f5c96c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9de3cf3b-fb3f-439e-88aa-72702817c119</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Role</value>
         <variableId>8978ec0b-d749-43ff-8c79-183805d3d17b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b38aede6-1156-4f58-8b77-4c2a31487309</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Cases_Final/Login and Signup/Striven_SignUp_WithoutData</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>717fe072-3b55-480b-bd80-c1a22aed94b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Cases_Final/Login and Signup/Striven_SignUP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>06c670c8-8c72-4dc9-8446-e4abda816d9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create a new user</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de4fa76-1864-4d5e-aa8a-70ad8f4f4342</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>086a27a9-05ed-4e07-8465-e17bddfdeac1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>311c2780-afd0-4352-a23f-fc00c2c42271</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcddbada-1d5e-422c-b810-55f7c48bb931</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b3cb3f6-19ff-4f44-ae2c-a1c680bd3044</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
