<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_ctl00ctl00mainContentmainCont_755761</name>
   <tag></tag>
   <elementGuidId>bf817880-6389-4291-8369-7b47780bc990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_mainContent_txtPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainContent_mainContent_txtPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dfbbe3e-270b-48f5-b8cf-042ca4526804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$txtPassword</value>
      <webElementGuid>156fffff-ab75-4ab5-9fd1-a29f37a6cd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e3e401c2-3b8a-4cc4-a918-ef4e1203b2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_mainContent_txtPassword</value>
      <webElementGuid>9f63ab9b-82ac-4624-b3ee-2c38142d7411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9ecd6978-d513-4125-b86a-7dedd5d9e781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>44461052-2d41-4057-82a3-c66fdea6439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_txtPassword&quot;)</value>
      <webElementGuid>71c9234f-6ad3-4ece-a726-5cf3b74ec89b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_mainContent_txtPassword']</value>
      <webElementGuid>aee7c9c5-d932-4a94-946c-1fc861b20370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_mainContent_pnlMemeberLogIn']/div/div/div[2]/input</value>
      <webElementGuid>87ffe7ac-ab85-483e-ba5a-02b42a8e1d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>40c3ba63-32cd-432b-a1d2-51462f1ea3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$mainContent$txtPassword' and @type = 'password' and @id = 'mainContent_mainContent_txtPassword' and @placeholder = 'Password']</value>
      <webElementGuid>a21d7611-8fbb-43ba-832b-65c5cb8a7de4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
