<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember this device for 30 days_ctl0_6a76c4</name>
   <tag></tag>
   <elementGuidId>1049fc05-e959-4d5a-9d66-d4a63214685a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_mainContent_mainContent_SubmitCodeButton_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_mainContent_mainContent_SubmitCodeButton_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>563b162b-0d99-4c16-920e-8b8fdd57406d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rbDecorated</value>
      <webElementGuid>2c790495-8b27-4a93-9773-99cdefa4b009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7d92063-e00a-4003-92e6-2448330987b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$SubmitCodeButton_input</value>
      <webElementGuid>d2b124da-cad7-4c65-a4f4-98d6d43806aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_mainContent_mainContent_SubmitCodeButton_input</value>
      <webElementGuid>b048fc45-65f5-4e05-b43f-59f5abad4e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>c0e5fc69-76f6-40e7-984a-ed85d8bf8c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9c975041-dcef-4b64-aed3-9118bf096871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_mainContent_mainContent_SubmitCodeButton_input&quot;)</value>
      <webElementGuid>52b91510-8512-46c0-b920-9b33391a671d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_mainContent_mainContent_SubmitCodeButton_input']</value>
      <webElementGuid>0d52190c-9dea-4838-9f11-5ab86f4e5d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ctl00_mainContent_mainContent_SubmitCodeButton']/input</value>
      <webElementGuid>30d257de-b567-4d0e-b4d3-9da7dcce34f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>5bed4626-5b61-4c2c-9389-2509aeb032f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'ctl00$ctl00$mainContent$mainContent$SubmitCodeButton_input' and @id = 'ctl00_ctl00_mainContent_mainContent_SubmitCodeButton_input']</value>
      <webElementGuid>396f889a-e069-4712-a9d0-47946e64dd09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
